In [4]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [5]:
spam = """
Hello,\nI saw your contact information on LinkedIn. I have carefully read through your profile and you seem to have an outstanding personality. This is one major reason why I am in contact with you. My name is Mr. Valery Grayfer Chairman of the Board of Directors of PJSC "LUKOIL". I am 86 years old and I was diagnosed with cancer 2 years ago. I will be going in for an operation later this week. I decided to WILL/Donate the sum of 8,750,000.00 Euros(Eight Million Seven Hundred And Fifty Thousand Euros Only etc. etc.
"""

ham = """
Hello,\nI am writing in regards to your application to the position of Data Scientist at Hooli X. We are pleased to inform you that you passed the first round of interviews and we would like to invite you for an on-site interview with our Senior Data Scientist Mr. John Smith. You will find attached to this message further information on date, time and location of the interview. Please let me know if I can be of any further assistance. Best Regards.
"""

In [6]:
print spam


Hello,
I saw your contact information on LinkedIn. I have carefully read through your profile and you seem to have an outstanding personality. This is one major reason why I am in contact with you. My name is Mr. Valery Grayfer Chairman of the Board of Directors of PJSC "LUKOIL". I am 86 years old and I was diagnosed with cancer 2 years ago. I will be going in for an operation later this week. I decided to WILL/Donate the sum of 8,750,000.00 Euros(Eight Million Seven Hundred And Fifty Thousand Euros Only etc. etc.



In [14]:
print ham


Hello,
I am writing in regards to your application to the position of Data Scientist at Hooli X. We are pleased to inform you that you passed the first round of interviews and we would like to invite you for an on-site interview with our Senior Data Scientist Mr. John Smith. You will find attached to this message further information on date, time and location of the interview. Please let me know if I can be of any further assistance. Best Regards.



In [8]:
cv = CountVectorizer()

In [15]:
#learn the vocabulary
cv.fit([spam, ham])


CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [16]:
cv.transform([spam, ham]).todense()

matrix([[1, 1, 1, 1, 1, 2, 2, 3, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 2,
         0, 0, 1, 1, 1, 1, 1, 2, 2, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 1, 0, 2,
         0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 4,
         1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
         1, 0, 0, 1, 0, 2, 2, 1, 1, 0, 2, 1, 1, 0, 1, 1, 2, 2, 0, 0, 2, 2, 2],
        [0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
         2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 1, 1, 0, 1, 1,
         1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 4,
         0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 0, 1,
         0, 1, 1, 0, 1, 3, 1, 0, 0, 1, 5, 0, 0, 2, 0, 0, 1, 1, 1, 1, 0, 4, 1]])

In [22]:
matrix = cv.fit_transform([spam, ham]).todense()

In [31]:
matrix.shape

matrix[:, 7]

matrix([[3],
        [2]])

In [35]:
import pandas as pd

df  = pd.DataFrame(cv.fit_transform([spam, ham]).todense(),
             columns=cv.get_feature_names())

df.transpose().sort_values(0, ascending=False).head(10).transpose()

of  and  your  in  is  contact  have  the  this  euros
0   4    3     2   2   2        2     2    2     2      2
1   4    2     1   1   0        0     0    3     1      0

In [26]:
import numpy as np

In [28]:
np.sum(matrix, axis = 0)

matrix([[1, 1, 1, 1, 1, 3, 3, 5, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2,
         2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 3,
         1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 8,
         1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1,
         1, 1, 1, 1, 1, 5, 3, 1, 1, 1, 7, 1, 1, 2, 1, 1, 3, 3, 1, 1, 2, 6, 3]])

In [39]:
easy_text = "I went to the zoo today. What do you think of that? I bet you hate it! Or maybe you don't"

easy_split_text = ["I went to the zoo today.",
                   "What do you think of that?",
                   "I bet you hate it!",
                   "Or maybe you don't"]

In [41]:
def simple_sentencer(text):
    '''take a string called `text` and return
    a list of strings, each containing a sentence'''

    sentences = []
    substring = ''
    for c in text:
        if c in ('.', '!', '?'):
            print substring
            sentences.append(substring + c)
            substring = ''
        else:
            print substring
            substring += c
    return sentences

simple_sentencer(easy_text)



I
I 
I w
I we
I wen
I went
I went 
I went t
I went to
I went to 
I went to t
I went to th
I went to the
I went to the 
I went to the z
I went to the zo
I went to the zoo
I went to the zoo 
I went to the zoo t
I went to the zoo to
I went to the zoo tod
I went to the zoo toda
I went to the zoo today

 
 W
 Wh
 Wha
 What
 What 
 What d
 What do
 What do 
 What do y
 What do yo
 What do you
 What do you 
 What do you t
 What do you th
 What do you thi
 What do you thin
 What do you think
 What do you think 
 What do you think o
 What do you think of
 What do you think of 
 What do you think of t
 What do you think of th
 What do you think of tha
 What do you think of that

 
 I
 I 
 I b
 I be
 I bet
 I bet 
 I bet y
 I bet yo
 I bet you
 I bet you 
 I bet you h
 I bet you ha
 I bet you hat
 I bet you hate
 I bet you hate 
 I bet you hate i
 I bet you hate it

 
 O
 Or
 Or 
 Or m
 Or ma
 Or may
 Or mayb
 Or maybe
 Or maybe 
 Or maybe y
 Or maybe yo
 Or maybe you
 Or maybe you 
 Or maybe yo

['I went to the zoo today.',
 ' What do you think of that?',
 ' I bet you hate it!']

In [ ]:
['I went to the zoo today.',
 ' What do you think of that?',
 ' I bet you hate it!']

In [42]:
from nltk.tokenize import PunktSentenceTokenizer
sent_detector = PunktSentenceTokenizer()
sent_detector.sentences_from_text(easy_text)


['I went to the zoo today.',
 'What do you think of that?',
 'I bet you hate it!',
 "Or maybe you don't"]

In [51]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
print stemmer.stem('Swimmed')
print stemmer.stem('Swimming')
print stemmer.stem('Swimmer')
print stemmer.stem('Swam')
print stemmer.stem('Scientist')
print stemmer.stem('Science')

Swim
Swim
Swimmer
Swam
Scientist
Scienc


In [58]:
from nltk.stem.snowball import SnowballStemmer

stemmer = SnowballStemmer('english')

stemmer.stem("generously")
stemmer.stem("scientist")
stemmer.stem("swam")
stemmer.stem("swimming")


u'swim'

In [65]:
tv = TfidfVectorizer()
mm = tv.fit_transform([spam, ham]).todense()

In [63]:
mm.shape

(2, 111)

In [66]:
mm

matrix([[ 0.09761636,  0.09761636,  0.09761636,  0.09761636,  0.09761636,
          0.13890968,  0.13890968,  0.20836453,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.06945484,
          0.        ,  0.09761636,  0.        ,  0.09761636,  0.09761636,
          0.09761636,  0.19523271,  0.        ,  0.        ,  0.09761636,
          0.09761636,  0.09761636,  0.09761636,  0.09761636,  0.19523271,
          0.19523271,  0.09761636,  0.        ,  0.        ,  0.06945484,
          0.        ,  0.09761636,  0.09761636,  0.19523271,  0.06945484,
          0.        ,  0.09761636,  0.        ,  0.13890968,  0.        ,
          0.06945484,  0.        ,  0.        ,  0.        ,  0.19523271,
          0.        ,  0.        ,  0.09761636,  0.        ,  0.        ,
          0.09761636,  0.        ,  0.09761636,  0.09761636,  0.        ,
          0.        ,  0.09761636,  0.06945484,  0.09761636,  0.09761636,
          0.27781937,  0.09761636,  0.