In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.shape

(5,)

In [29]:
d = np.array([[1,3,5],[7,9,11]])

In [30]:
d.shape

(2, 3)

In [23]:
b = np.array([[1, 2, 3, 4],[5, 6,3,5],[7,8,9, 12]])

In [24]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  3,  5],
       [ 7,  8,  9, 12]])

In [25]:
b.shape

(3, 4)

In [26]:
np.reshape(b, (2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 3,  5,  7,  8,  9, 12]])

In [31]:
np.reshape(b, (1, 12))

array([[ 1,  2,  3,  4,  5,  6,  3,  5,  7,  8,  9, 12]])

In [32]:
b.T

array([[ 1,  5,  7],
       [ 2,  6,  8],
       [ 3,  3,  9],
       [ 4,  5, 12]])

In [33]:
b[0:12]

array([[ 1,  2,  3,  4],
       [ 5,  6,  3,  5],
       [ 7,  8,  9, 12]])

In [37]:
b[:1]

array([[1, 2, 3, 4]])

In [38]:
b[2:]

array([[ 7,  8,  9, 12]])

In [39]:
b[1]

array([5, 6, 3, 5])

In [47]:
b[1:3, 3:]

array([[ 5],
       [12]])

In [51]:
b[1:, 2:3]

array([[3],
       [9]])