In [61]:
# import numpy
# create array x
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])
print x

[1 2 3 4 5 6]


In [62]:
# print the shape of x
print x.shape

(6,)


In [63]:
# create a two dimensional array
x2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print x2d

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [64]:
# print shape of 2d array
print x2d.shape

(4, 3)


In [65]:
# reshape the array to 2 x 6
np.reshape(x2d, (2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [66]:
# reshape the array to 1 x 12
np.reshape(x2d, (1, 12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [67]:
# transpose the array
x2d.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [68]:
# indexing method 1
x2d[0]

array([1, 2, 3])

In [69]:
# indexing method 2
x2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
# indexing method 3
x2d[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
# indexing method 4

In [72]:
# indexing method 5

In [73]:
# indexing method 6