In [44]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

In [45]:
iris.feature_names
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10')

In [46]:
df = pd.DataFrame(X, columns=iris.feature_names)
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [47]:
df["badfeature1"] = 5*np.random.randn(150)+3
df["badfeature2"] = np.random.rand(150)
df["badfeature3"] = np.random.randn(150)*-1 -0.5

In [48]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   badfeature1  badfeature2  badfeature3  
0     6.932508     0.972141    -1.479758  
1     4.479640     0.354399     0.419466  
2     1.656470     0.970451    -1.239690  
3    -8.371294     0.513462    -1.864537  
4     8.268674     0.383970    -1.113499

In [50]:
df["class"] = y

In [53]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   badfeature1  badfeature2  badfeature3  class  
0     6.932508     0.972141    -1.479758      0  
1     4.479640     0.354399     0.419466      0  
2     1.656470     0.970451    -1.239690      0  
3    -8.371294     0.513462    -1.864537      0  
4     8.268674     0.383970    -1.113499      0

## Using built-in correlation function from pandas dataframe

In [57]:
df.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.109369           0.871754   
sepal width (cm)           -0.109369          1.000000          -0.420516   
petal length (cm)           0.871754         -0.420516           1.000000   
petal width (cm)            0.817954         -0.356544           0.962757   
badfeature1                -0.134881         -0.013059          -0.085350   
badfeature2                -0.020976          0.001926          -0.070662   
badfeature3                -0.080945         -0.065253          -0.043296   
class                       0.782561         -0.419446           0.949043   

                   petal width (cm)  badfeature1  badfeature2  badfeature3  \
sepal length (cm)          0.817954    -0.134881    -0.020976    -0.080945   
sepal width (cm)          -0.356544    -0.013059     0.001926    -0.065253   
petal length (cm)          0.962757    -0.085350    -0.070662    -0.043296   
petal width (cm)           1.000000    -0.099245    -0.064935    -0.059599   
badfeature1               -0.099245     1.000000     0.007628     0.183636   
badfeature2               -0.064935     0.007628     1.000000     0.066909   
badfeature3               -0.059599     0.183636     0.066909     1.000000   
class                      0.956464    -0.044330    -0.063300    -0.036653   

                      class  
sepal length (cm)  0.782561  
sepal width (cm)  -0.419446  
petal length (cm)  0.949043  
petal width (cm)   0.956464  
badfeature1       -0.044330  
badfeature2       -0.063300  
badfeature3       -0.036653  
class              1.000000

In [59]:
df.corr(method="kendall")

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.072112           0.717624   
sepal width (cm)           -0.072112          1.000000          -0.182391   
petal length (cm)           0.717624         -0.182391           1.000000   
petal width (cm)            0.654960         -0.146988           0.803014   
badfeature1                -0.113236         -0.023785          -0.055947   
badfeature2                -0.012380          0.004646          -0.051217   
badfeature3                -0.058803         -0.057977          -0.033022   
class                       0.670444         -0.333435           0.822949   

                   petal width (cm)  badfeature1  badfeature2  badfeature3  \
sepal length (cm)          0.654960    -0.113236    -0.012380    -0.058803   
sepal width (cm)          -0.146988    -0.023785     0.004646    -0.057977   
petal length (cm)          0.803014    -0.055947    -0.051217    -0.033022   
petal width (cm)           1.000000    -0.067395    -0.039732    -0.039360   
badfeature1               -0.067395     1.000000    -0.004027     0.106040   
badfeature2               -0.039732    -0.004027     1.000000     0.058076   
badfeature3               -0.039360     0.106040     0.058076     1.000000   
class                      0.838757    -0.029929    -0.049591    -0.028182   

                      class  
sepal length (cm)  0.670444  
sepal width (cm)  -0.333435  
petal length (cm)  0.822949  
petal width (cm)   0.838757  
badfeature1       -0.029929  
badfeature2       -0.049591  
badfeature3       -0.028182  
class              1.000000

## Using SelectKBest and Chi2 from scikit-learn

In [35]:
from sklearn.feature_selection import SelectKBest, chi2

In [62]:
X = df[df.columns[0:-1]]
y = df["class"]

skb = SelectKBest(k=3)
skb.fit_transform(X, y)

skb.get_support()

array([ True, False,  True,  True, False, False, False], dtype=bool)

In [63]:
#Chi2 statistical test does not work on negative features
chi2(X,y)

ValueError: Input X must be non-negative.

In [64]:
Xpos = X[[df.columns[0], df.columns[1], df.columns[2], df.columns[3], df.columns[5]]]
chi2(Xpos, y)

(array([  10.81782088,    3.59449902,  116.16984746,   67.24482759,
           0.15394315]),
 array([  4.47651499e-03,   1.65754167e-01,   5.94344354e-26,
          2.50017968e-15,   9.25916173e-01]))

## Using Regularization (Model Building)

In [65]:
from sklearn.linear_model import LogisticRegression, LassoCV


In [74]:
lasso = LassoCV(fit_intercept=False)

In [75]:
X.head()
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [76]:
lasso.fit(X, y)
lasso.coef_

array([-0.09178327, -0.02396113,  0.30825078,  0.37297614,  0.00440578,
       -0.        ,  0.        ])

In [73]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              