In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [13]:
a.shape


(5,)

In [14]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [15]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
c.shape

(2, 5)

In [17]:
a + b

array([6, 6, 6, 6, 6])

In [18]:
a + 1

array([2, 3, 4, 5, 6])

In [19]:
5*a

array([ 5, 10, 15, 20, 25])

In [20]:
np.add(a,b)

array([6, 6, 6, 6, 6])

In [21]:
np.subtract(a,b)

array([-4, -2,  0,  2,  4])

In [22]:
np.dot(a,b)

35

In [25]:
a.dot(b)

35

In [26]:
np.zeros((100,100))

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [28]:
np.ones((50,50))

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [30]:
8*np.ones((50,50))

array([[ 8.,  8.,  8., ...,  8.,  8.,  8.],
       [ 8.,  8.,  8., ...,  8.,  8.,  8.],
       [ 8.,  8.,  8., ...,  8.,  8.,  8.],
       ..., 
       [ 8.,  8.,  8., ...,  8.,  8.,  8.],
       [ 8.,  8.,  8., ...,  8.,  8.,  8.],
       [ 8.,  8.,  8., ...,  8.,  8.,  8.]])

In [32]:
np.eye(50)

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [35]:
a = np.array([[0,3,5],[5,5,2]])
b = np.array([[3,4],[3,-2],[4,-2]])

In [37]:
a.dot(b)

array([[ 29, -16],
       [ 38,   6]])

In [39]:
f = np.array([90, 45, 32, 107])

In [45]:
(f-32)*5./9

array([ 32.22222222,   7.22222222,   0.        ,  41.66666667])

In [47]:
type(f)

numpy.ndarray

In [51]:
def ftoc(f):
    return (f-32)*5./9

In [56]:
lis = [1,2,3,4,5,6]

In [57]:
lis[1:4]

[2, 3, 4]

In [58]:
a[0]

90

In [59]:
a

array([ 90,  45,  32, 107])

In [60]:
a[0]

90

In [63]:
a[0:2]

array([90, 45])

In [64]:
c = np.eye(50)

In [65]:
c[0,0]

1.0

In [66]:
c[(0,0)]

1.0

In [67]:
c[0:5, 0:5]

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [68]:
np.random.random((10,10))

array([[ 0.92084811,  0.02174441,  0.14536266,  0.95903578,  0.36612132,
         0.16346017,  0.8088063 ,  0.79697515,  0.94560437,  0.01559353],
       [ 0.37446165,  0.13070401,  0.27384969,  0.31504926,  0.58332213,
         0.21330583,  0.21485058,  0.83723889,  0.96579836,  0.65026783],
       [ 0.75431403,  0.88656865,  0.91439368,  0.87538795,  0.51735579,
         0.43577195,  0.86670674,  0.72835291,  0.55400423,  0.71413933],
       [ 0.32126222,  0.5108188 ,  0.43226627,  0.77203549,  0.3143602 ,
         0.00382468,  0.67614232,  0.14432469,  0.65839755,  0.69978205],
       [ 0.33561291,  0.18003329,  0.51716353,  0.84820631,  0.87110549,
         0.25902263,  0.79864205,  0.15187461,  0.10653163,  0.22983008],
       [ 0.19262186,  0.22909733,  0.5887915 ,  0.80515244,  0.54992577,
         0.5060228 ,  0.15060843,  0.76612378,  0.57899256,  0.84762425],
       [ 0.05809346,  0.57372965,  0.23926176,  0.65382759,  0.40816138,
         0.17976049,  0.70215985,  0.42027752

Help on built-in function random_sample:

random_sample(...)
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_sample())
    <type 'float'>
    >>> n

In [79]:
c[:1, 0:1] = 20

In [85]:
c[0:2, 0:10] = 20

In [87]:
c

array([[ 20.,  20.,  20., ...,   0.,   0.,   0.],
       [ 20.,  20.,  20., ...,   0.,   0.,   0.],
       [  0.,   0.,   1., ...,   0.,   0.,   0.],
       ..., 
       [  0.,   0.,   0., ...,   1.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   1.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   1.]])

In [89]:
d = c == 20

In [90]:
type(d)

numpy.ndarray

In [93]:
d

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ..., 
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], dtype=bool)

In [94]:
20*d

array([[20, 20, 20, ...,  0,  0,  0],
       [20, 20, 20, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [96]:
10*d

array([[10, 10, 10, ...,  0,  0,  0],
       [10, 10, 10, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ..., 
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [97]:
1*d

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [98]:
1.0*d

array([[ 1.,  1.,  1., ...,  0.,  0.,  0.],
       [ 1.,  1.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [103]:
ones = np.ones((5,6))

In [104]:
np.sum(ones)

30.0

In [105]:
ones

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [106]:
np.sum(ones, axis = 0)

array([ 5.,  5.,  5.,  5.,  5.,  5.])

In [107]:
np.sum(ones, axis = 1)

array([ 6.,  6.,  6.,  6.,  6.])

In [111]:
ones


array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [112]:
ones.T

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])